### ISSUE TITLE
Create updated homepage template to reflect the new design

### ISSUE THREAD

**Issue by jayperryworks** [biveeco/biveeco.github.io#13]
Based on the new mockups, visual design, etc., update the middleman templates for the homepage for the new layout and UI.

- [x] rough out overall layout
- [x] header/main nav layout
- [x] cover layout & image treatment
- [x] footer/contact layout
- [x] case studies listings
  - [x] populate template data
  - [x] style cards
  - [x] fluid aspect images
- [x] staff listings (see #16)
- [x] refactor `gallery` UI component to work with new staff and case study listings
- [x] update color themes

**Comment by jayperryworks** [comment]
@sschafft For the sake of speed, I'm going to consider the 'watercolor' effects (painted/messy edges, background textures) shown in the mockups out of scope in this issue. That will be slightly tricky and worth doing on a second pass, in a separate issue.

Priority-wise, I'm aiming to have basic layout in place for homepage, case study, and portraits by fri. If I can add polishes like the textures by then, great, but if not it's an enhancement we can add later.

**Comment by sschafft** [comment]
Agreed. That makes a lot of sense to me.
