### ISSUE TITLE
Initial "codeable" mockups & visual design of site

### ISSUE THREAD

**Issue by sschafft** [biveeco/biveeco.github.io#8]
- [x] Home page mockups
- [x] Case study mockups
- [x] Type treatment
- [x] Scale
- [x] Buttons 
- [x] Colors

**Comment by jayperryworks** [comment]
@NestorFuentes @sschafft Here's some cleaned-up mockups of the homepage, at each screen size.

Note, I pulled a slightly quieter watercolor texture into the header/hero unit, but it's still a rough placeholder for "blue sky painted into the drawing."

### Small phone (320px)
![home-small](https://user-images.githubusercontent.com/1044536/36002429-24cc9742-0cf8-11e8-9174-561ebdcbc653.png)

### Tablet/small laptop (1024px)
![home-medium](https://user-images.githubusercontent.com/1044536/36002428-24c36f8c-0cf8-11e8-88c9-5b6c654122b2.png)

## Desktop (2000px)
![home-large](https://user-images.githubusercontent.com/1044536/36002427-24b9809e-0cf8-11e8-9b77-b72f03835308.png)

**Comment by jayperryworks** [comment]
Tomorrow I'll flesh out the type treatments, scale, buttons, etc., and will work on the case studies next week.

**Comment by sschafft** [comment]
This is awesome!~

**Comment by jayperryworks** [comment]
I have some initial stuff for scale, color palette, etc. in `drive > library > collateral > rev-2.0 > branding`. There's a sketch library in there called `bivee-brand-library` with a bunch of symbols we can use on any collateral.

**Comment by sschafft** [comment]
Oh awesome!

Cheers,
Scott Schaffter
MANAGING DIRECTOR, BIVEE INC
e: scott@bivee.co t: 202.258.2640

**Comment by jayperryworks** [comment]
@NestorFuentes I'm leaning toward making the "blue kuri" color (midtone) a little more blue/purple. Feels a little better in the mockups - it talks a little more to "blackberry." Will see how it feels in the browser.

**Comment by jayperryworks** [comment]
Also sketch libraries are the best thing ever.

**Comment by jayperryworks** [comment]
@sschafft @NestorFuentes Here's a first pass at the case study mockup.

![case_study-small](https://user-images.githubusercontent.com/1044536/36566506-ac45f3fe-17f1-11e8-8342-87dc34059303.png)

**Comment by sschafft** [comment]
Awesome. Thats great!

**Comment by jayperryworks** [comment]
@NestorFuentes @hcline BTW should mention that the mockup above uses sections/headings (background, results, etc.) from earlier content drafts and Nestor's mockups, but they're just placeholders. The site is structured so that case studies can have any number of sections in any order, with images, videos, etc. placed anywhere you like.

I think we can also set up templates so that you can configure background colors, etc. for each section.

**Comment by jayperryworks** [comment]
@NestorFuentes @sschafft if it's okay with you guys, I'm going to go ahead and close this - there's still feedback coming in but the mockups are at a place that's workable. I can address any new feedback (including Nestor's last markups) in the code.

**Comment by sschafft** [comment]
Agreed
