### ISSUE TITLE
Build case study content into site

### ISSUE THREAD

**Issue by sschafft** [biveeco/biveeco.github.io#9]
- [x] Finalize case study copy - GFDRR Sendai
- [x] Finalize case study copy - CGAP
- [x] Finalize case study copy - DDH (?)
- [x] Finalize case study copy - PPP (?)

Content Approval SS: 
- [ ] Finalize case study copy - GFDRR Sendai
- [ ] Finalize case study copy - CGAP
- [ ] Finalize case study copy - DDH (?)
- [ ] Finalize case study copy - PPP (?)

Content approval JP: 
- [ ] Finalize case study copy - GFDRR Sendai
- [ ] Finalize case study copy - CGAP
- [ ] Finalize case study copy - DDH (?)
- [ ] Finalize case study copy - PPP (?)

Content approval NF: 
- [ ] Finalize case study copy - GFDRR Sendai
- [ ] Finalize case study copy - CGAP
- [ ] Finalize case study copy - DDH (?)
- [ ] Finalize case study copy - PPP (?)

Migrate content to HTML / Markdown things: 
- [ ] GFDRR Sendai
- [x] CGAP
- [x] DDH (?)
- [x] PPP (?)

**Comment by hcline** [comment]
@jayperryworks @sschafft @NestorFuentes GFDRR case study content is ready for first review - https://docs.google.com/document/d/1Wc-oknIt7idUCa4vEj6dkBKSTUStWJyMeCmVoK1aD5g/edit#heading=h.thk8tong4ymw

**Comment by hcline** [comment]
@jayperryworks @NestorFuentes @sschafft CGAP case study also ready for review - https://docs.google.com/document/d/164hxbdYahuqqJVLkuIEjuHUYwneR-ZMGRooq7k1QM0s/edit#
